name: Wesley Shields
title: Wesley Shields
logo: images/wxs.png
description: Security Engineer interested in malware, protocols and reverse engineering. Retired FreeBSD committer. I also climb on fake rocks.
footer-links:
  twitter: wxs
  github: wxsbsd
theme: jekyll-theme-minimal
site:
  github:
  is_project_page: false
