title: Wesley Shields
logo: images/chuck.jpg
description: Security Engineer interested in malware, protocols and reverse engineering. Retired FreeBSD committer. I also climb on fake rocks.
theme: jekyll-theme-minimal
